name: first-github-action
on: [push]
jobs:
  deploy-to-vm:
    runs-on: ubuntu-latest
    steps:
      
      - name: Deploy to VM
        run: rsync -avz . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/ttnew