name: first-github-action
on: [push]
jobs:
  deploy-to-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          Key: ${{ secrets.MY_RSA_KEY }}
          known_host: 'Just a placeholder for real host'
      - name: Adding Known Hosts
        run: ssh-keyscan -H $ {{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to VM
        run: rsync -avz . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/ttnew